# Tensors

**REF: [freeCodeCamp](https://www.freecodecamp.org/learn/machine-learning-with-python/tensorflow/introduction-to-tensorflow)

"A tensor is a generalization of vector and matrices to potentially higher dimensions. Internally, TensorFlow represents tensors as n-dimensional arrays of base datatypes."(https://www.tensorflow.org/guide/tensor)

It shouldn't surprise you that tensors are a fundamental aspect of TensorFlow. They are the main objects that are passed around and manipulated through the program. Each tensor represents a partialy defined computation that will eventually produce a value. TensorFlow programs work by building a graph of Tensor objects that details how tensors are related. Running different parts of the graph allow results to be generated.

Each tensor has a data type and a shape.

**Data Types Include**: float32, int32, string and others.
**Shape**: Represents the dimensions of data.

## Creating Tensors

Below is an example of how to create some different tensors.

In [6]:
import tensorflow as tf

string  = tf.Variable("this is a string", tf.string)
number = tf.Variable(324, tf.int16)
floating = tf.Variable(3.567, tf.float64)

## Rank/Degree of Tensors

Another word for rank is degree, these terms simply mean the number of dimensions involved in the tensor. What we created above is a tensor of rank 0, also known as a scalar.

Now we'll create some tensors of higher degrees/ranks.

In [7]:
rank_1_tensor = tf.Variable(["teste", "hello"], tf.string)
rank_2_tensor = tf.Variable([["test", "ok", "wow"], ["test", "yes", "yup"]], tf.string)

**To determine the rank** of a tensor, we can call the following method

In [8]:
tf.rank(rank_2_tensor)

<tf.Tensor: shape=(), dtype=int32, numpy=2>

## Shape of Tensors

Now that we've talked about the rank of tensors, it's time to talk about the shape. The shape of a tensor is simply the amount of elements that exist in each dimension. TensorFlow will try to determine the shape of a tensor, but sometimes it may be unknown.

To **get the shape** of a tensor we use the shape attribute.

In [9]:
rank_2_tensor.shape

TensorShape([2, 3])

### Changing Shape

The number of elements of a tensor is the product of the sizes of all its shapes. There are often many shapes that have the same number of elements, making it convinient to be able to change the shape of a tensor.

The example below shows how to change the shape of a tensor.

In [10]:
tensor1 = tf.ones([1, 2, 3])                # Creates a shape[1, 2, 3] tensor full of ones
tensor2 = tf.reshape(tensor1, [2, 3, 1])    # Reshape existing data to shape [2, 3, 1]
tensor3 = tf.reshape(tensor2, [3, -1])      # -1 tells the tensor to calculate the size of the dimension int that place
                                            # in this case, this will reshape the tensor to [3, 2]

# The number of elemets in the reshaped tensor MUST match the number in the original tensor

Now let's have a look at our different tensors.

In [13]:
print("Tensor1: \n", tensor1, "\n")
print("Tensor2: \n", tensor2, "\n")
print("Tensor3: \n", tensor3, "\n")

# Notice the changes in shape

Tensor1: 
 tf.Tensor(
[[[1. 1. 1.]
  [1. 1. 1.]]], shape=(1, 2, 3), dtype=float32) 

Tensor2: 
 tf.Tensor(
[[[1.]
  [1.]
  [1.]]

 [[1.]
  [1.]
  [1.]]], shape=(2, 3, 1), dtype=float32) 

Tensor3: 
 tf.Tensor(
[[1. 1.]
 [1. 1.]
 [1. 1.]], shape=(3, 2), dtype=float32) 



## Types of Tensors

Before we go too far, I will mention that there are different types of tensors. These are the most commonly used and we will talk more in depth about each as they are used.

* Variable
* Constant
* Placeholder
* SparseTensor

With the exception of `Variable` all of these tensors are immutable, meaning their value may not change during execution.

For now it is sufficient to understand that we use the `Variable` tensor when we want to potentially change the value of our tensor.

## Evaluating Tensors

There will be some times throughout this guide that we need to evaluate a tensor. In other words, get its value. Since tensors represents a partially complete computation, we will, sometimes, need to run what's called a *session* to evaluate the tensor.

There are many different ways to achieve this, but I will note the simplest way below.

In [ ]:
with tf.compat.v1.Session() as sess:    # Creates a session using the default graph
    tensor.eval()                       # Tensor will of course be the name of your tensor

In the code above we evaluated the tensor variable that was stored in the **default graph**. The default graph holds all operations not specifified to any other graph. It is possible to create our own separate graphs, but for now, we will stick with the default.

# Sources

Most of the information is taken directly from the TensorFlow website, which can be found below.

https://www.tensorflow.org/guide/tensor

In [18]:
import tensorflow as tf

print(tf.version)

t = tf.zeros([5, 5, 5, 5])
print("t: \n", t, "\n")

t = tf.reshape(t, [125, -1])
print("Reshaped t: \n", t, "\n")

<module 'tensorflow._api.v2.version' from '/home/unudunno/.local/lib/python3.10/site-packages/tensorflow/_api/v2/version/__init__.py'>
t: 
 Tensor("zeros:0", shape=(5, 5, 5, 5), dtype=float32) 

Reshaped t: 
 Tensor("Reshape:0", shape=(125, 5), dtype=float32) 

